os: osx
before_install:
  - brew update
  - brew --env
  - brew config
install:
  - mkdir -p $(brew --repo)/Library/Taps/johnmccabe
  - ln -s $TRAVIS_BUILD_DIR $(brew --repo)/Library/Taps/johnmccabe/homebrew-openfaas-bitbar
script:
  - ./test.sh